### ISSUE TITLE
Nitpick about /run

### ISSUE THREAD

**Issue by stephane** [jberkus/annotated.conf#3]
I think `/run` is the new standard (https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) and `/var/run/` a symlink on it.
https://github.com/jberkus/annotated.conf/blob/1fda67930f6bf058b7ea96c9e023febfdebee35d/extra.10.conf#L71

Not really that important BTW!
Thank you for your useful repo.

**Comment by jberkus** [comment]
Oops!  I actually updated that, and then failed to push the update.  Thanks for catching it!

**Comment by jberkus** [comment]
Fixed in commit 29f3949. Thanks!
